### ISSUE TITLE
Linked documentation is not up to date with UI form

### ISSUE THREAD

**Issue by Halama** [keboola/dynamodb-extractor#17]
Parameters node is mentioned in documentation but UI already expects only body of parameters.

![image](https://user-images.githubusercontent.com/903531/47378915-ca0f4800-d6f9-11e8-912f-2b0a649790ee.png)

**Comment by Halama** [comment]
omg, to už je screen z té doc. Tak podle mě asi ok.

**Comment by ujovlado** [comment]
Mozem to este poladit, ak treba ... `parameters` tam teoreticky uvadzat nemusim, my interne vieme, ze to tam ma byt.

**Comment by Halama** [comment]
jo, jako může tenhle doc být ready pro UI když ho linkujeme. Já jsem první totiž myslel že to co mi poslal nakreslili oni a ne že to byl jen screen te doc:)

**Comment by ujovlado** [comment]
Ano, je to matuce, kuknem ten PR
